spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alimentation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: congo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Utilisé pour mettre à jour le schéma de la base de données
    show-sql: true # Affiche les requêtes SQL dans la console

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false # Ignore les erreurs de sérialisation sur les beans vides

  logging:
    level:
      org.hibernate.SQL: DEBUG # Affiche les requêtes SQL générées par Hibernate
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Affiche les valeurs liées aux requêtes SQL

  transaction:
    rollback-on-commit-failure: true # Annule la transaction en cas d'échec lors de la validation

  web:
    cors:
      allowed-origins: "*" # Permet toutes les origines (peut être limité en production)
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Configuration des propriétés de l'application
app:
  name: ALIMENTATION
  version: 1.0.0

